import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Button,
  Container,
  Typography,
} from '@mui/material'

import ExampleImage from '../../public/enigma/TseTCbC.png'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dishonored 2 Door Training - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Typography mt="1rem">
            Welcome to the Dishonored 2 door Training. This aim to help you to open the gate as fast
            as possible
          </Typography>
          <Typography variant="h2" sx={{ fontSize: '1.6rem', textAlign: 'center' }}>
            Need some help ?
          </Typography>
          <Accordion>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="panel1a-content"
              id="panel1a-header"
            >
              <Typography>Example</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <div style={{ display: 'flex', justifyContent: 'center' }}>
                <Image
                  src={ExampleImage}
                  alt="Example Image"
                  style={{ width: '75%', height: 'auto' }}
                />
              </div>
            </AccordionDetails>
          </Accordion>
          <Button href="/quizz" variant="contained" fullWidth sx={{ mt: 3, mb: 2 }}>
            Go
          </Button>
        </Container>
      </main>
    </>
  )
}
