import { Box, Button, Container, Typography } from '@mui/material'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dishonored 2 Door Training - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          sx={{
            marginTop: 8,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
          }}
        >
          <Typography variant="h1">Dishonored 2 Door Training</Typography>
          <Container maxWidth="xs">
            <Box component="form" onSubmit={() => {}} noValidate sx={{ mt: 1 }}>
              <Typography className="m-4">
                Welcome to the Dishonored 2 door Training. This aim to help you to open the gate as
                fast as possible
              </Typography>
              <Button href="/quizz" variant="contained" fullWidth sx={{ mt: 3, mb: 2 }}>
                Go
              </Button>
            </Box>
          </Container>
        </Box>
      </main>
    </>
  )
}
